version: "3"

services:
  db:
    image: mysql:5.7
    ports:
      - 32000:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  website:
    build: ./site
    volumes:
      - ./site:/var/www/html
    ports:
      - 80:80
    depends_on:
      - db
    links:
      - db