CREATE DATABASE IF NOT EXISTS raya;
use raya;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    uuid VARCHAR(8) NOT NULL,
    profile_image VARCHAR(255) NOT NULL
);